// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL7zFzFw0ujllLkqE17nblTrhsJJTmKsM',
    appId: '1:1050353663667:web:22f928ec343f8e4d74fac6',
    messagingSenderId: '1050353663667',
    projectId: 'kuiz-52388',
    authDomain: 'kuiz-52388.firebaseapp.com',
    storageBucket: 'kuiz-52388.appspot.com',
    measurementId: 'G-C13JCBQJET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClhIpvChsX95PcK98lbZqxE5kONdXiEb4',
    appId: '1:1050353663667:android:b0d554825b07936774fac6',
    messagingSenderId: '1050353663667',
    projectId: 'kuiz-52388',
    storageBucket: 'kuiz-52388.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0t-Q3Yby0PsnHPm1q-GVCYogxUod_avA',
    appId: '1:1050353663667:ios:5107ad544b508b1274fac6',
    messagingSenderId: '1050353663667',
    projectId: 'kuiz-52388',
    storageBucket: 'kuiz-52388.appspot.com',
    iosBundleId: 'com.kuiz.kuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0t-Q3Yby0PsnHPm1q-GVCYogxUod_avA',
    appId: '1:1050353663667:ios:5107ad544b508b1274fac6',
    messagingSenderId: '1050353663667',
    projectId: 'kuiz-52388',
    storageBucket: 'kuiz-52388.appspot.com',
    iosBundleId: 'com.kuiz.kuiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL7zFzFw0ujllLkqE17nblTrhsJJTmKsM',
    appId: '1:1050353663667:web:e51ff7020427c53174fac6',
    messagingSenderId: '1050353663667',
    projectId: 'kuiz-52388',
    authDomain: 'kuiz-52388.firebaseapp.com',
    storageBucket: 'kuiz-52388.appspot.com',
    measurementId: 'G-J894G4SV3E',
  );
}
